#!/bin/bash
# Quick fix checklist for Raspberry Pi "Unknown Machine" issue

echo "╔════════════════════════════════════════════════════════════════╗"
echo "║     RASPBERRY PI UNKNOWN MACHINE - QUICK FIX CHECKLIST        ║"
echo "╚════════════════════════════════════════════════════════════════╝"

echo ""
echo "STEP 1: Run Diagnostic"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "$ python diagnose_rpi_issues.py"
echo ""
echo "This will tell you exactly what's wrong. Look for:"
echo "  ❌ Database machines without IP - Need to add IP addresses"
echo "  ❌ API endpoint issues - Need to restart Flask or check code"
echo ""

echo "STEP 2: Fix Database (if needed)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Run these SQL commands in MySQL:"
echo ""
echo "-- Add columns (run only once)"
echo "ALTER TABLE machines ADD COLUMN ip_address VARCHAR(50) NULL UNIQUE;"
echo "ALTER TABLE machines ADD COLUMN machine_name VARCHAR(200) NULL;"
echo "ALTER TABLE machines ADD COLUMN zone VARCHAR(100) NULL;"
echo ""
echo "-- Add IP for each Raspberry Pi machine"
echo "UPDATE machines SET ip_address = '10.110.30.15' WHERE machine_code = 'M001';"
echo "UPDATE machines SET ip_address = '10.110.30.16' WHERE machine_code = 'M002';"
echo ""

echo "STEP 3: Check Raspberry Pi IP Address"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "On Raspberry Pi, run:"
echo "$ hostname -I"
echo ""
echo "This shows the Pi's IP (example: 10.110.30.15)"
echo "Make sure this exact IP is in the 'machines' table!"
echo ""

echo "STEP 4: Verify Flask is Running"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "From command line, test API:"
echo "$ curl http://YOUR_FLASK_IP:5000/api/events/machines/list"
echo ""
echo "Should return JSON with machines, not connection error"
echo ""

echo "STEP 5: Fix Raspberry Pi Code (raspberrycode.py)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Find line 44 and change:"
echo "FROM: MAIN_API_BASE_URL = \"http://10.110.30.15:1250/api\""
echo "TO:   MAIN_API_BASE_URL = \"http://[YOUR_FLASK_IP]:5000/api\""
echo ""
echo "Example (if Flask is at 192.168.1.100):"
echo "MAIN_API_BASE_URL = \"http://192.168.1.100:5000/api\""
echo ""

echo "STEP 6: Restart Flask App"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "$ python main.py"
echo ""

echo "STEP 7: Run Raspberry Pi Code"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "On Raspberry Pi:"
echo "$ python raspberrycode.py"
echo ""
echo "You should see:"
echo "  ✓ Retrieved IP address: 10.110.30.15"
echo "  ✓ Retrieved machine name: M001"
echo "  System started for M001"
echo ""

echo "STEP 8: Verify Events"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "$ python check_events_quick.py M001"
echo ""
echo "Should show events being recorded"
echo ""

echo "═══════════════════════════════════════════════════════════════════"
echo "If you still have issues, run:"
echo "$ python diagnose_rpi_issues.py"
echo "And share the output"
echo "═══════════════════════════════════════════════════════════════════"
